### ISSUE TITLE
[Feature] Perhaps automatic restart should not be performed after the update is completed

### ISSUE THREAD

**Issue by YCZ01111** [SteamClientHomebrew/Millennium#132]
### Before Requesting

- [X] I found no existing issue matching my feature request
- [X] This request is related to Millennium, and not a request for a specific theme/addon

### Describe the feature you'd like!

In China, due to ISP settings, checking for updates and downloading Millennium can be very slow, which can result in early loading of SteamUI. During playing games, if Millennium detects an update or the latest version has been downloaded, it may cause Steam to automatically restart. Perhaps tasks related to Millennium updates should not be performed during SteamUI's work period, or automatic restarts should not be performed after the update is completed.
Of course, I know how to set check_for-updates to no, but doing so may cause errors on port 8080 for a few people. Until now, we still don't know why port 8080 is related to check_for-updates.

**Comment by shdwmtr** [comment]
The issue with port 8080 should have been fixed last update. I'll see what do-able with the updates issue though.

**Comment by YCZ01111** [comment]
The Millennium version I am currently sharing with my audience is 2.12.3, but a few people still encounter the issue with port 8080 due to set check_for-updates to no. I haven't noticed anyone else reporting this issue, but it doesn't seem like it's caused by a Chinese ISP either.

**Comment by shdwmtr** [comment]
there is a 2.12.4
