### ISSUE TITLE
[Bug] Millennium requires opening up Steam twice to start successfully

### ISSUE THREAD

**Issue by Jonius7** [SteamClientHomebrew/Millennium#149]
### Before Reporting

- [X] I found no existing issues matching my bug
- [x] My issue is not caused by a theme
- [X] My issue is not caused by a plugin

### Describe the Bug

Been using v2.12.4 for a while and I find I need to start up Steam twice for it to open properly as the first time it crashes or doesn't show any Steam windows.

Below is the `-dev` console when Steam is run for the first time, something about a `Promise already satisfied`

![2024-10-28 17_24_32-Millennium@v2 12 4](https://github.com/user-attachments/assets/9b606475-03de-4a39-9919-30cb0340249c)

### Expected Behavior

Start up Steam
See login screen and then Steam window the first time

### Steps To Reproduce

Windows 11, with Inject JavaScript and Inject StyleSheets enabled, and these themes/skins:
- ATOMS
- Classic Steam Library
- Metro by Rose
- OldGlory
- Simple Dark.
- SpaceTheme for Steam

### Operating System

Windows

**Comment by shdwmtr** [comment]
I've seemingly fixed this, it will be in the latest update. Steam added something in the newest beta that causes this.

**Comment by NathanL1370** [comment]
I can confirm I am having this issue too. This is also occurring on the stable branch, and it also happens with the default theme.

**Comment by shdwmtr** [comment]
@NathanL1370 @Jonius7 

Try using this version, see if it fixes it. 
https://nightly.link/SteamClientHomebrew/Millennium/actions/runs/11566730508

Extract the files in your steam folder and replace all (make sure Steam is closed)

**Comment by NathanL1370** [comment]
Seems like it's fixed after trying the version from the nightly link. Restarts also seem to work properly now, including the default and other themes.

**Comment by shdwmtr** [comment]
Perfect; after some more slight bug testing I'll release that version. You can use that version as normal in the time being ofc.

**Comment by YCZ01111** [comment]
I found that after starting Windows for a period of time, Steam can start successfully in one go. If you run Steam right after starting Windows, you will need to run it twice.

**Comment by shdwmtr** [comment]
Fixed in the latest release!

**Comment by YCZ01111** [comment]
I have updated to 2.13.0, but there is still this issue

**Comment by NathanL1370** [comment]
Issue is still happening after updating to 2.13.0 on Windows.
Uninstalling and reinstalling Millennium does not fix the issue; now Steam won't start up at all.

**Comment by shdwmtr** [comment]
@NathanL1370 start steam with -dev and share the console output

**Comment by shdwmtr** [comment]
@YCZ01111 @NathanL1370 give this a try. Just extract and replace in the steam folder 
https://github.com/SteamClientHomebrew/Millennium/actions/runs/11648759524

**Comment by NathanL1370** [comment]
> @NathanL1370 start steam with -dev and share the console output. Btw I thought you said the nightly link fixed your issue?

![Screenshot 2024-11-02 222904](https://github.com/user-attachments/assets/d06d7050-6848-4f34-b61d-25dc4cf8a066)

Console output now throws a system error, with the `what()` function saying that a resource is temporarily unavailable.

**Comment by NathanL1370** [comment]
@shdwmtr Forgot to include this screenshot, but when I tried using your compiled version of Millennium, the console output warns that it's "upgrading" from 2.13.1 to 2.13.0, which still has the bug. (Technically, wouldn't it be downgrading in this case?)
Steam was started with -dev. 
![Screenshot 2024-11-02 223941](https://github.com/user-attachments/assets/b98b1fb1-656f-4cab-b85f-d25a6d33ce96)

**Comment by shdwmtr** [comment]
Ah oopsies, it's downloading the live version. Set `check_for_updates` to `no` in `C:\Program Files (x86)\Steam\ext\millennium.ini` for testing (and revert back when necessary). Then install the build above

**Comment by NathanL1370** [comment]
Trying again with 3 launch attempts, console still throws `std::system_error`.
![Screenshot 2024-11-02 231030](https://github.com/user-attachments/assets/8e3b06e8-4187-44f0-b89e-f7226b7bb4f9)
![Screenshot 2024-11-02 231049](https://github.com/user-attachments/assets/5ba49376-31a0-4473-b078-a7efe92679ce)
![Screenshot 2024-11-02 231116](https://github.com/user-attachments/assets/1c642437-1677-4523-b5fd-350f05c8a508)

**Comment by shdwmtr** [comment]
I seem to be able to reproduce it, its because you have a large amount of files in your steamui folder in steam that slows down Millenniums start process resulting in a race condition. Where it says connected to SharedJSContext in 7000 ms it should be 1-2 ms

**Comment by shdwmtr** [comment]
It seems I wasn't properly freeing a thread. This should fix it https://github.com/SteamClientHomebrew/Millennium/actions/runs/11654025051

**Comment by NathanL1370** [comment]
> I seem to be able to reproduce it, its because you have a large amount of files in your steamui folder in steam that slows down Millenniums start process resulting in a race condition. Where it says connected to SharedJSContext in 7000 ms it should be 1-2 ms

That was my actual issue upon further inspection in my steamui folder, it seems I had a bunch of skin backup folders that were probably created in a very old version of Millennium.

**Comment by NathanL1370** [comment]
Seems to be working now after trying your hotfixed version.
Console output also reports that the UI has loaded successfully as well. Restarts are working properly as it should.
![Screenshot 2024-11-03 113127](https://github.com/user-attachments/assets/06acba71-8e6c-418d-9499-6350c1ecddb7)

**Comment by shdwmtr** [comment]
try restoring those files to see if it works even with them in there now (if you havent deleted them permanently)

**Comment by NathanL1370** [comment]
> try restoring those files to see if it works even with them in there now (if you havent deleted them permanently)

Seems like it still works, it's just that Steam will end up taking longer to start with the files present.

Before:
![Screenshot 2024-11-03 114321](https://github.com/user-attachments/assets/4d8dea4c-5b2d-4b9f-b071-b76346b102c8)
After:
![Screenshot 2024-11-03 114408](https://github.com/user-attachments/assets/411936e8-7f55-49a0-a615-14336011f958)

**Comment by shdwmtr** [comment]
Perfect! I plan to move skins outside of the steamui folder in the future because Steam pre-caches everything in the folder which takes a long time (happens with or without Millennium), but that's an issue for another time.
